apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: {{ include "podchaosmonkey.clusterrole" . }}

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
